lb_port: 8080
strategy: round-robin
backends:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"
  - "http://localhost:8084"

healthcheck_interval: 20   # seconds
backend_timeout: 2 # seconds
shutdown_timeout: 10 # seconds